import 'dart:ui';

class Piloto {
  final String nome;
  final String equipe;
  final int numero;
  final String fotoPerfil;
  final int pontuacao;
  final String nacionalidade;
  final String nomeArquivoBandeira;
  final int idade;
  final int polePositions;
  final String voltaMaisRapida;
  final int podios;
  final Color corEquipe;

  Piloto({
    required this.nome,
    required this.equipe,
    required this.numero,
    required this.fotoPerfil,
    required this.pontuacao,
    required this.nacionalidade,
    required this.nomeArquivoBandeira,
    required this.idade,
    required this.polePositions,
    required this.voltaMaisRapida,
    required this.podios,
    required this.corEquipe,
  });
}

  final List<Piloto> pilotos = [
    Piloto(
      nome: 'LANDO NORRIS',
      equipe: 'MCLAREN',
      numero: 4,
      fotoPerfil: 'assets/images_pilot/lando-norris-driver-ratings-20.webp',
      pontuacao: 254,
      nacionalidade: 'Inglaterra',
      nomeArquivoBandeira: 'reino_unido',
      idade: 23,
      polePositions: 20,
      voltaMaisRapida: '4',
      podios: 6,
      corEquipe: const Color(0xFFFF8000),
    ),
    Piloto(
      nome: 'MAX VERSTAPEN',
      equipe: 'RED BULL RACING',
      numero: 1,
      fotoPerfil: 'assets/images_pilot/max-verstappen-driver-ratings-.webp',
      pontuacao: 313,
      nacionalidade: 'Holanda',
      nomeArquivoBandeira: 'holanda',
      idade: 25,
      polePositions: 20,
      voltaMaisRapida: '5',
      podios: 7,
      corEquipe: const Color(0xFF3671C6),
    ),
    Piloto(
      nome: 'SERGIO PEREZ',
      equipe: 'RED BULL RACING',
      numero: 11,
      fotoPerfil: 'assets/images_pilot/sergio-perez-driver-ratings-20.webp',
      pontuacao: 143,
      nacionalidade: 'Mexico',
      nomeArquivoBandeira: 'mexico',
      idade: 25,
      polePositions: 20,
      voltaMaisRapida: '5',
      podios: 7,
      corEquipe: const Color(0xFF3671C6),
    ),
    Piloto(
      nome: 'GEORGE RUSSELL',
      equipe: 'MERCEDES',
      numero: 63,
      fotoPerfil: 'assets/images_pilot/george-russell-driver-ratings-.webp',
      pontuacao: 143,
      nacionalidade: 'Inglaterra',
      nomeArquivoBandeira: 'reino_unido',
      idade: 25,
      polePositions: 20,
      voltaMaisRapida: '5',
      podios: 7,
      corEquipe: const Color(0xFF27F4D2),
    ),
    Piloto(
      nome: 'LEWIS HAMILTON',
      equipe: 'MERCEDES',
      numero: 44,
      fotoPerfil: 'assets/images_pilot/lewis-hamilton-driver-ratings-.webp',
      pontuacao: 166,
      nacionalidade: 'Inglaterra',
      nomeArquivoBandeira: 'reino_unido',
      idade: 25,
      polePositions: 20,
      voltaMaisRapida: '5',
      podios: 7,
      corEquipe: const Color(0xFF27F4D2),
    ),
    Piloto(
      nome: 'CHARLES LECLERC',
      equipe: 'FERRARI',
      numero: 16,
      fotoPerfil: 'assets/images_pilot/charles-leclerc-driver-ratings.webp',
      pontuacao: 235,
      nacionalidade: 'Monaco',
      nomeArquivoBandeira: 'Monaco',
      idade: 25,
      polePositions: 20,
      voltaMaisRapida: '5',
      podios: 7,
      corEquipe: const Color(0xFFE8002D),
    ),
    Piloto(
      nome: 'CARLOS SAINZ',
      equipe: 'FERRARI',
      numero: 55,
      fotoPerfil: 'assets/images_pilot/carlos-sainz-driver-ratings-20.webp',
      pontuacao: 184,
      nacionalidade: 'Espanha',
      nomeArquivoBandeira: 'spain',
      idade: 25,
      polePositions: 20,
      voltaMaisRapida: '5',
      podios: 7,
      corEquipe: const Color(0xFFE8002D),
    ),
    Piloto(
      nome: 'ALEXANDER ALBON',
      equipe: 'WILLIANS',
      numero: 23,
      fotoPerfil: 'assets/images_pilot/alexander-albon-driver-ratings.webp',
      pontuacao: 12,
      nacionalidade: 'Tailandia',
      nomeArquivoBandeira: 'Thailand',
      idade: 25,
      polePositions: 20,
      voltaMaisRapida: '5',
      podios: 7,
      corEquipe: const Color(0xFF64C4FF),
    ),
    Piloto(
      nome: 'OSCAR PIASTRI',
      equipe: 'MCLAREN',
      numero: 81,
      fotoPerfil: 'assets/images_pilot/oscar-piastri-driver-ratings-2.webp',
      pontuacao: 222,
      nacionalidade: 'Australia',
      nomeArquivoBandeira: 'Australia',
      idade: 25,
      polePositions: 20,
      voltaMaisRapida: '5',
      podios: 7,
      corEquipe: const Color(0xFFFF8000),
    ),
    Piloto(
      nome: 'FERNANDO ALONSO',
      equipe: 'ASTON MARTIN',
      numero: 14,
      fotoPerfil: 'assets/images_pilot/fernando-alonso-driver-ratings.webp',
      pontuacao: 58,
      nacionalidade: 'Espanha',
      nomeArquivoBandeira: 'spain',
      idade: 25,
      polePositions: 20,
      voltaMaisRapida: '5',
      podios: 7,
      corEquipe: const Color(0xFF229971),
    ),
    Piloto(
      nome: 'LANCE STROLL',
      equipe: 'ASTON MARTIN',
      numero: 18,
      fotoPerfil: 'assets/images_pilot/lance-stroll-driver-ratings-20.webp',
      pontuacao: 24,
      nacionalidade: 'Canada',
      nomeArquivoBandeira: 'Canada',
      idade: 25,
      polePositions: 20,
      voltaMaisRapida: '5',
      podios: 7,
      corEquipe: const Color(0xFF229971),
    ),
    Piloto(
      nome: 'NICO HULKENGERG',
      equipe: 'HAAS',
      numero: 20,
      fotoPerfil: 'assets/images_pilot/nico-hulkenberg-driver-ratings.webp',
      pontuacao: 22,
      nacionalidade: 'Alemanha',
      nomeArquivoBandeira: 'germany',
      idade: 25,
      polePositions: 20,
      voltaMaisRapida: '5',
      podios: 7,
      corEquipe: const Color(0xFFB6BABD),
    ),
    Piloto(
      nome: 'YUKI TSUNODA',
      equipe: 'RB',
      numero: 22,
      fotoPerfil: 'assets/images_pilot/yuki-tsunoda-driver-ratings-20.webp',
      pontuacao: 22,
      nacionalidade: 'Japão',
      nomeArquivoBandeira: 'japao',
      idade: 25,
      polePositions: 20,
      voltaMaisRapida: '5',
      podios: 7,
      corEquipe: const Color(0xFF6692FF),
    ),
    Piloto(
      nome: 'DANIEL RICCIARDO',
      equipe: 'RB',
      numero: 3,
      fotoPerfil: 'assets/images_pilot/daniel-ricciardo-driver-rating.webp',
      pontuacao: 12,
      nacionalidade: 'Australia',
      nomeArquivoBandeira: 'Australia',
      idade: 25,
      polePositions: 20,
      voltaMaisRapida: '5',
      podios: 7,
      corEquipe: const Color(0xFF6692FF),
    ),
    Piloto(
      nome: 'PIERRE GASLY',
      equipe: 'ALPINE',
      numero: 10,
      fotoPerfil: 'assets/images_pilot/pierre-gasly-driver-ratings-20.webp',
      pontuacao: 8,
      nacionalidade: 'França',
      nomeArquivoBandeira: 'frança',
      idade: 25,
      polePositions: 20,
      voltaMaisRapida: '5',
      podios: 7,
      corEquipe: const Color(0xFFFF87BC),
    ),
    Piloto(
      nome: 'OLIVER BEARMAN',
      equipe: 'HAAS',
      numero: 50,
      fotoPerfil: 'assets/images_pilot/oliver-bearman-driver-ratings-.webp',
      pontuacao: 7,
      nacionalidade: 'Inglaterra',
      nomeArquivoBandeira: 'reino_unido',
      idade: 25,
      polePositions: 20,
      voltaMaisRapida: '5',
      podios: 7,
      corEquipe: const Color(0xFFB6BABD),
    ),
    Piloto(
      nome: 'KEVIN MAGNUSSEN',
      equipe: 'HAAS',
      numero: 18,
      fotoPerfil: 'assets/images_pilot/kevin-magnussen-driver-ratings.webp',
      pontuacao: 6,
      nacionalidade: 'Dinamarca',
      nomeArquivoBandeira: 'Dinamarca',
      idade: 25,
      polePositions: 20,
      voltaMaisRapida: '5',
      podios: 7,
      corEquipe: const Color(0xFFB6BABD),
    ),
    Piloto(
      nome: 'ESTEBAN OCON',
      equipe: 'ALPINE',
      numero: 31,
      fotoPerfil: 'assets/images_pilot/esteban-ocon-driver-ratings-20.webp',
      pontuacao: 5,
      nacionalidade: 'França',
      nomeArquivoBandeira: 'frança',
      idade: 25,
      polePositions: 20,
      voltaMaisRapida: '5',
      podios: 7,
      corEquipe: const Color(0xFFFF87BC),
    ),
    Piloto(
      nome: 'ZHOU GUANYU',
      equipe: 'KICK SAUBER',
      numero: 24,
      fotoPerfil: 'assets/images_pilot/zhou-guanyu-driver-ratings-202.webp',
      pontuacao: 0,
      nacionalidade: 'China',
      nomeArquivoBandeira: 'China',
      idade: 25,
      polePositions: 20,
      voltaMaisRapida: '5',
      podios: 7,
      corEquipe: const Color(0xFF52E252),
    ),
    Piloto(
      nome: 'LOGAN SARGEANT',
      equipe: 'WILLIAMS',
      numero: 2,
      fotoPerfil: 'assets/images_pilot/logan-sargeant-driver-ratings-.webp',
      pontuacao: 0,
      nacionalidade: 'Estados Unidos',
      nomeArquivoBandeira: 'estados_unidos',
      idade: 25,
      polePositions: 20,
      voltaMaisRapida: '5',
      podios: 7,
      corEquipe: const Color(0xFF64C4FF),

    ),
    Piloto(
      nome: 'FRANCO COLAPINTO',
      equipe: 'WILLIAMS',
      numero: 43,
      fotoPerfil: 'assets/images_pilot/franco-colapinto.png',
      pontuacao: 4,
      nacionalidade: 'Argentina',
      nomeArquivoBandeira: 'argentina',
      idade: 25,
      polePositions: 20,
      voltaMaisRapida: '5',
      podios: 7,
      corEquipe: const Color(0xFF64C4FF),
    ),
    Piloto(
      nome: 'VALTTERI BOTTAS',
      equipe: 'KICK SAUBER',
      numero: 77,
      fotoPerfil: 'assets/images_pilot/valtteri-bottas-driver-ratings.webp',
      pontuacao: 0,
      nacionalidade: 'Finlândia',
      nomeArquivoBandeira: 'Finlandia',
      idade: 25,
      polePositions: 20,
      voltaMaisRapida: '5',
      podios: 7,
      corEquipe: const Color(0xFF52E252),
    ),
  ];


